export enum RuStoreProductType {
  NON_CONSUMABLE,
  CONSUMABLE,
  SUBSCRIPTION,
}

export enum RuStoreProductStatus {
  ACTIVE,
  INACTIVE,
}

export enum RuStorePurchaseState {
  CREATED = 'CREATED',
  INVOICE_CREATED = 'INVOICE_CREATED',
  CONFIRMED = 'CONFIRMED',
  PAID = 'PAID',
  CANCELLED = 'CANCELLED',
  CONSUMED = 'CONSUMED',
  CLOSED = 'CLOSED',
  TERMINATED = 'TERMINATED',
}
